/**
 * Authored 7GC campus catalog.
 * Room lists are local to each planning brief. Shared navigation is allowed;
 * shared room lists are not. Gaza has no coordinates. Graham is remote-first.
 */

export const SOURCE_DOC = 'docs/campus/7GC_CAMPUS_SOURCE_REQUIREMENTS.md';
export const SOURCE_COMPANION = '7GC_DIGITAL_CAMPUS_SOURCE_REQUIREMENTS.md';

export const TRUTH_STATES = Object.freeze([
  'DIGITAL_TWIN',
  'PROPOSED',
  'PARTNER_REFERENCE',
  'OPERATIONAL_EVIDENCE',
]);

export const COVERAGE_STATES = Object.freeze([
  'IMPLEMENTED_SPATIALLY',
  'IMPLEMENTED_FUNCTIONALLY',
  'IMPLEMENTED_BOTH',
  'PLANNED_NOT_YET_IMPLEMENTED',
  'NOT_APPLICABLE',
  'BLOCKED_BY_REAL_WORLD_VALIDATION',
]);

export const EVIDENCE_STATES = Object.freeze([
  'PROPOSAL',
  'SIMULATION',
  'PARTNER_REFERENCE',
  'FIELD_VALIDATED',
]);

export const WAIKE_CONTRACT_SURFACES = Object.freeze([
  'today',
  'continue',
  'courses',
  'assignments',
  'grades',
  'calendar',
  'study',
  'ask_gunnchai',
]);

export const TOP_LEVEL_SITES = Object.freeze(['HOME', 'CAMPUS', 'GALLERY']);

export const CAMPUS_LANDING = Object.freeze([
  { id: 'my-waike', label: 'My WAIKE / Today', route: '#/mlv/campus/academic/today' },
  { id: 'academic-center', label: 'Academic Center', route: '#/mlv/campus/academic' },
  { id: 'library', label: 'Library', route: '#/mlv/campus/library' },
  { id: 'study-rooms', label: 'Study Rooms', route: '#/mlv/campus/study' },
  { id: 'lecture-hall', label: 'Lecture Hall', route: '#/mlv/campus/lecture' },
  { id: 'media-center', label: 'Media Center', route: '#/mlv/campus/media' },
  { id: 'atlas', label: '7GC Atlas', route: '#/mlv/campus/atlas' },
]);

function room(key, name, extra = {}) {
  return {
    key,
    name,
    kind: extra.kind || 'ROOM',
    function: extra.function || name,
    waike: extra.waike || [],
    specialist: extra.specialist === true,
    coverage: extra.coverage || 'IMPLEMENTED_BOTH',
    evidence: extra.evidence || 'PROPOSAL',
    geometry: extra.geometry || 'AUTHORED_PLANNING_LAYOUT',
  };
}

const SHARED_CAMPUS_PROGRAM = [
  room('WAIKE_ACADEMIC_CENTER', 'WAIKE Academic Center', {
    kind: 'SURFACE',
    function: 'Campus surface that consumes the WAIKE contract without duplicating LMS data',
    waike: [...WAIKE_CONTRACT_SURFACES],
    coverage: 'IMPLEMENTED_FUNCTIONALLY',
  }),
  room('TODAY_CONTINUE_COURSES', 'Today / Continue / Courses / Assignments / Grades / Calendar', {
    kind: 'SURFACE',
    function: 'Direct WAIKE contract consumption for learner rhythm',
    waike: ['today', 'continue', 'courses', 'assignments', 'grades', 'calendar'],
    coverage: 'IMPLEMENTED_FUNCTIONALLY',
  }),
  room('DIRECT_NAVIGATION', 'Direct / non-spatial navigation', {
    kind: 'NAVIGATION',
    function: 'Every major campus function reachable without 3D walking',
    coverage: 'IMPLEMENTED_FUNCTIONALLY',
  }),
  room('LIST_MAP_MODE', 'Accessible list / map mode', {
    kind: 'NAVIGATION',
    function: 'Keyboard, controller, touch, and reduced-motion list/map equivalent',
    coverage: 'IMPLEMENTED_FUNCTIONALLY',
  }),
  room('PUBLIC_COMMON_STUDY', 'Public / common study', {
    kind: 'ROOM',
    function: 'Shared study surface that never reads Home PRIVATE files',
  }),
  room('INSTANCED_STUDY_ROOMS', 'Instanced study rooms', {
    kind: 'ROOM',
    function: 'Unlimited instanced study rooms with explicit ACL',
    coverage: 'IMPLEMENTED_BOTH',
  }),
  room('LOCAL_CONTEXT_PANEL', 'Local / regional context panel', {
    kind: 'SURFACE',
    function: 'Site-specific planning identity and wayfinding, not a palette swap',
    coverage: 'IMPLEMENTED_FUNCTIONALLY',
  }),
  room('PHASE_SELECTOR', 'Phase selector', {
    kind: 'SURFACE',
    function: 'Expose planning phases instead of implying a finished physical campus',
    coverage: 'IMPLEMENTED_FUNCTIONALLY',
  }),
  room('EVIDENCE_STATUS_PANEL', 'Evidence / status panel', {
    kind: 'SURFACE',
    function: 'Distinguish proposal, simulation, partner reference, and field-validated evidence',
    coverage: 'IMPLEMENTED_FUNCTIONALLY',
  }),
];

export const CAMPUS_CATALOG = [
  {
    id: 'GARY',
    slug: 'gary',
    name: 'WAIKE Gary UPNOW',
    atlas_name: 'Gary',
    planning_identity: 'Flagship civic technology and workforce campus rooted in Gary, Indiana.',
    planning_model: 'CIVIC_WORKFORCE_FLAGSHIP',
    local_focus: 'Civic resilience, workforce, apprenticeship, public dashboards',
    truth_state: 'PROPOSED',
    character: [
      'bright', 'safe', 'serious', 'youth-friendly', 'adult-respectful', 'hands-on',
      'local', 'high-tech without sterility', 'professional without intimidation', 'community-rooted',
    ],
    wayfinding: [
      'Gary steel / civic resilience references',
      'warm + high-tech accents',
      'student project walls',
      'local maps',
      'before/after project boards',
      'Build → Ship → Document → Present',
      'public dashboards',
    ],
    avoid: [],
    layout: 'CIVIC_HALL_AND_PROJECT_CORRIDOR',
    phases: [
      { id: 'PILOT', token: 'PILOT', label: 'Minimum pilot' },
      { id: 'SEMI_PERMANENT', token: 'SEMI', label: 'Preferred semi-permanent' },
      { id: 'FULL', token: 'FULL', label: 'Full digital campus' },
    ],
    rooms: {
      PILOT: [
        room('FLEXIBLE_CLASSROOM', 'Flexible classroom', { waike: ['courses'] }),
        room('DEVICE_HELP_DESK_TABLE', 'Device / help desk table', { waike: ['study'] }),
        room('MOBILE_HARDWARE_CART', 'Mobile hardware cart', { specialist: true, waike: ['courses'] }),
        room('MOBILE_NETWORKING_CYBER_CART', 'Mobile networking / cyber cart', { specialist: true, waike: ['courses'] }),
        room('PRESENTATION_WALL', 'Presentation wall / screen', { waike: ['calendar'] }),
        room('SECURE_STORAGE', 'Secure storage'),
        room('QUIET_SUPPORT_AREA', 'Quiet support area', { waike: ['study'] }),
        room('STAFF_PLANNING_TABLE', 'Staff planning table'),
      ],
      SEMI: [
        room('FLEXIBLE_CLASSROOM_A', 'Flexible classroom A', { waike: ['courses'] }),
        room('FLEXIBLE_CLASSROOM_B', 'Flexible classroom B', { waike: ['courses'] }),
        room('DEVICE_BAR', 'Device bar', { waike: ['study'] }),
        room('HARDWARE_REPAIR_LAB', 'Hardware / repair lab', { specialist: true, waike: ['courses'] }),
        room('NETWORKING_CYBER_LAB', 'Networking / cyber lab', { specialist: true, waike: ['courses'] }),
        room('AI_CLOUD_STUDIO', 'AI / cloud studio', { specialist: true, waike: ['courses'] }),
        room('CAREER_PORTFOLIO_STUDIO', 'Career / portfolio studio', { specialist: true, waike: ['grades'] }),
        room('COMMUNITY_ROOM', 'Community room', { waike: ['calendar'] }),
        room('STAFF_OFFICE', 'Staff office'),
        room('STORAGE_WORKROOM', 'Storage / workroom'),
        room('STUDENT_LOUNGE', 'Student lounge / decompression', { waike: ['study'] }),
      ],
      FULL: [
        room('MULTI_ROOM_LEARNING_HUB', 'Multi-room learning hub', { waike: ['courses'] }),
        room('DEDICATED_LABS', 'Dedicated labs', { specialist: true, waike: ['courses'] }),
        room('HARDWARE_REPAIR_LAB', 'Hardware / repair lab', { specialist: true, waike: ['courses'] }),
        room('COMMUNITY_EVENT_SPACE', 'Community event space', { waike: ['calendar'] }),
        room('APPRENTICESHIP_PROJECT_STUDIO', 'Apprenticeship / project studio', { specialist: true, waike: ['assignments'] }),
        room('RESEARCH_DIGITAL_TWIN_OPS', 'Research + digital twin operations', { specialist: true, waike: ['courses'] }),
        room('SHOWCASE_DEMO_GALLERY', 'Showcase / demo gallery', { specialist: true }),
        room('SECURE_DEVICE_DEPOT', 'Secure device depot'),
        room('PARTNER_MEETING_ROOMS', 'Partner meeting rooms'),
        room('HYBRID_LEARNING_STUDIO', 'Hybrid learning / recording studio', { waike: ['courses'] }),
        room('LECTURE_EVENT_SPACE', 'Lecture / event space', { waike: ['calendar'] }),
        room('MEDIA_SOCIAL_CENTER', 'Media / social center'),
      ],
    },
    extra_shared: [
      room('PROJECT_WALLS', 'Student project walls', { kind: 'WAYFINDING', function: 'Before/after project boards in civic corridor' }),
      room('LOCAL_MAPS', 'Local maps', { kind: 'WAYFINDING', function: 'Gary civic context, not a claimed facility survey' }),
      room('PUBLIC_DASHBOARDS', 'Public dashboards', { kind: 'SURFACE', function: 'Workforce / civic progress boards' }),
    ],
  },
  {
    id: 'GHANA',
    slug: 'ghana',
    name: 'WAIKE Ghana UPNOW',
    atlas_name: 'Ghana',
    planning_identity: 'Ghana-led civic / workforce / technology campus; first anchor concept Accra–Tema, but not Accra-only.',
    planning_model: 'GHANA_LED_CIVIC_WORKFORCE',
    local_focus: 'Ghana-led learning, mentor workspace, regional pop-up support',
    truth_state: 'PROPOSED',
    character: [
      'Ghanaian', 'bright', 'safe', 'practical', 'youth-friendly', 'adult-respectful',
      'hands-on', 'professional', 'high-tech without sterility', 'community-rooted', 'global without foreignness',
    ],
    wayfinding: ['courtyard learning cluster', 'mentor wall', 'regional pop-up kit board'],
    avoid: ['foreign-branch styling', 'imported campus clone'],
    layout: 'COURTYARD_LEARNING_CLUSTER',
    phases: [
      { id: 'PILOT', token: 'PILOT', label: 'Minimum pilot' },
      { id: 'SEMI_PERMANENT', token: 'SEMI', label: 'Preferred semi-permanent' },
      { id: 'FULL', token: 'FULL', label: 'Full digital campus' },
    ],
    rooms: {
      PILOT: [
        room('FLEXIBLE_CLASSROOM', 'Flexible classroom', { waike: ['courses'] }),
        room('DEVICE_HELP_DESK', 'Device / help desk', { waike: ['study'] }),
        room('MOBILE_HARDWARE_CART', 'Mobile hardware cart', { specialist: true }),
        room('MOBILE_NETWORKING_CYBER_CART', 'Mobile networking / cyber cart', { specialist: true }),
        room('PRESENTATION_WALL', 'Presentation wall'),
        room('SECURE_STORAGE', 'Secure storage'),
        room('QUIET_SUPPORT', 'Quiet support', { waike: ['study'] }),
        room('STAFF_PLANNING', 'Staff planning'),
        room('HYBRID_LEARNING_RECORDING', 'Hybrid learning / recording', { waike: ['courses'] }),
      ],
      SEMI: [
        room('FLEXIBLE_CLASSROOM_A', 'Flexible classroom A', { waike: ['courses'] }),
        room('FLEXIBLE_CLASSROOM_B', 'Flexible classroom B', { waike: ['courses'] }),
        room('DEVICE_BAR', 'Device bar'),
        room('HARDWARE_REPAIR_LAB', 'Hardware / repair lab', { specialist: true }),
        room('NETWORKING_CYBER_LAB', 'Networking / cyber lab', { specialist: true }),
        room('AI_CLOUD_STUDIO', 'AI / cloud studio', { specialist: true }),
        room('CAREER_PORTFOLIO_STUDIO', 'Career / portfolio studio', { specialist: true, waike: ['grades'] }),
        room('COMMUNITY_ROOM', 'Community room'),
        room('STAFF_OFFICE', 'Staff office'),
        room('STORAGE_WORKROOM', 'Storage / workroom'),
        room('STUDENT_LOUNGE', 'Student lounge / decompression'),
        room('SMALL_MEDIA_HYBRID_STUDIO', 'Small media / hybrid learning studio', { waike: ['courses'] }),
      ],
      FULL: [
        room('MULTI_ROOM_LEARNING_HUB', 'Multi-room learning hub'),
        room('DEDICATED_LABS', 'Dedicated labs', { specialist: true }),
        room('COMMUNITY_EVENT_SPACE', 'Community event space'),
        room('APPRENTICESHIP_PROJECT_STUDIO', 'Apprenticeship / project studio', { specialist: true }),
        room('RESEARCH_DIGITAL_TWIN_OPS', 'Research + digital twin operations', { specialist: true }),
        room('SHOWCASE_DEMO_GALLERY', 'Showcase / demo gallery', { specialist: true }),
        room('SECURE_DEVICE_DEPOT', 'Secure device depot'),
        room('PARTNER_MEETING_ROOMS', 'Partner meeting rooms'),
        room('HYBRID_LEARNING_STUDIO', 'Hybrid learning / recording studio'),
        room('REGIONAL_POPUP_LAB_STORAGE', 'Regional pop-up lab storage', { specialist: true }),
        room('MENTOR_WORKSPACE', 'Mentor / visiting instructor workspace', { specialist: true }),
        room('LECTURE_EVENT_SPACE', 'Lecture / event space'),
        room('MEDIA_SOCIAL_CENTER', 'Media / social center'),
      ],
    },
    extra_shared: [],
  },
  {
    id: 'GUYANA',
    slug: 'guyana',
    name: 'WAIKE Guyana UPNOW',
    atlas_name: 'Guyana',
    planning_identity: 'Guyana-led learning / workforce / climate-resilience node; Georgetown–Demerara as first anchor concept with deliberate national reach.',
    planning_model: 'CLIMATE_RESILIENCE_LEARNING_NODE',
    local_focus: 'Climate / GIS, energy / logistics, river-aware public dashboard',
    truth_state: 'PROPOSED',
    character: [
      'Guyanese', 'bright', 'safe', 'practical', 'youth-friendly', 'adult-respectful',
      'climate-aware', 'river-aware', 'hands-on', 'professional',
    ],
    wayfinding: ['river-aware linear campus', 'climate wall', 'community learning dashboard'],
    avoid: [],
    layout: 'RIVER_AWARE_LINEAR_CAMPUS',
    phases: [
      { id: 'PILOT', token: 'PILOT', label: 'Minimum pilot' },
      { id: 'SEMI_PERMANENT', token: 'SEMI', label: 'Preferred semi-permanent' },
      { id: 'FULL', token: 'FULL', label: 'Full digital campus' },
    ],
    rooms: {
      PILOT: [
        room('FLEXIBLE_CLASSROOM', 'Flexible classroom', { waike: ['courses'] }),
        room('DEVICE_HELP_DESK', 'Device / help desk'),
        room('MOBILE_HARDWARE_CART', 'Mobile hardware cart', { specialist: true }),
        room('MOBILE_NETWORKING_CYBER_CART', 'Mobile networking / cyber cart', { specialist: true }),
        room('CLIMATE_GIS_WORKSTATION', 'Climate / GIS workstation', { specialist: true, waike: ['courses'] }),
        room('PRESENTATION_WALL', 'Presentation wall'),
        room('SECURE_STORAGE', 'Secure storage'),
        room('QUIET_SUPPORT', 'Quiet support'),
        room('STAFF_PLANNING', 'Staff planning'),
        room('HYBRID_LEARNING_RECORDING', 'Hybrid learning / recording'),
      ],
      SEMI: [
        room('FLEXIBLE_CLASSROOM_A', 'Flexible classroom A'),
        room('FLEXIBLE_CLASSROOM_B', 'Flexible classroom B'),
        room('DEVICE_BAR', 'Device bar'),
        room('HARDWARE_REPAIR_LAB', 'Hardware / repair lab', { specialist: true }),
        room('NETWORKING_CYBER_LAB', 'Networking / cyber lab', { specialist: true }),
        room('AI_CLOUD_STUDIO', 'AI / cloud studio', { specialist: true }),
        room('CLIMATE_GIS_DATA_STUDIO', 'Climate + GIS data studio', { specialist: true, waike: ['courses'] }),
        room('ENERGY_LOGISTICS_STUDIO', 'Energy / logistics systems studio', { specialist: true, waike: ['courses'] }),
        room('CAREER_PORTFOLIO_STUDIO', 'Career / portfolio studio', { specialist: true }),
        room('COMMUNITY_ROOM', 'Community room'),
        room('STAFF_OFFICE', 'Staff office'),
        room('STORAGE_WORKROOM', 'Storage / workroom'),
        room('STUDENT_LOUNGE', 'Student lounge / decompression'),
        room('SMALL_MEDIA_HYBRID_STUDIO', 'Small media / hybrid learning studio'),
      ],
      FULL: [
        room('MULTI_ROOM_LEARNING_HUB', 'Multi-room learning hub'),
        room('DEDICATED_LABS', 'Dedicated labs', { specialist: true }),
        room('COMMUNITY_EVENT_SPACE', 'Community event space'),
        room('APPRENTICESHIP_PROJECT_STUDIO', 'Apprenticeship / project studio', { specialist: true }),
        room('CLIMATE_GIS_STUDIO', 'Climate / GIS + digital twin studio', { specialist: true, waike: ['courses'] }),
        room('ENERGY_LOGISTICS_INDUSTRY_STUDIO', 'Energy / logistics + industry systems studio', { specialist: true }),
        room('RESEARCH_DIGITAL_TWIN_OPS', 'Research + digital twin operations', { specialist: true }),
        room('SHOWCASE_DEMO_GALLERY', 'Showcase / demo gallery', { specialist: true }),
        room('SECURE_DEVICE_DEPOT', 'Secure device depot'),
        room('PARTNER_MEETING_ROOMS', 'Partner meeting rooms'),
        room('HYBRID_LEARNING_STUDIO', 'Hybrid learning / recording studio'),
        room('REGIONAL_POPUP_LAB_STORAGE', 'Regional pop-up lab storage', { specialist: true }),
        room('MENTOR_WORKSPACE', 'Mentor / visiting instructor workspace', { specialist: true }),
        room('PUBLIC_DASHBOARD_WALL', 'Public dashboard / community learning wall', { specialist: true }),
        room('LECTURE_EVENT_SPACE', 'Lecture / event space'),
        room('MEDIA_SOCIAL_CENTER', 'Media / social center'),
      ],
    },
    extra_shared: [],
  },
  {
    id: 'GEELONG',
    slug: 'geelong',
    name: 'WAIKE Geelong UPNOW',
    atlas_name: 'Geelong',
    planning_identity: 'Geelong-rooted design/build, manufacturing, health-tech, port/logistics, clean-energy, creative-tech and applied-engineering node.',
    planning_model: 'DESIGN_BUILD_APPLIED_INDUSTRY',
    local_focus: 'Design/build prototyping, applied industry, industry briefing',
    truth_state: 'PROPOSED',
    character: [
      'Geelong-rooted', 'design-aware', 'bright', 'safe', 'practical', 'youth-friendly',
      'adult-respectful', 'hands-on', 'professional', 'industrial but welcoming', 'high-tech without sterility',
    ],
    wayfinding: ['workshop yard', 'prototype wall', 'industry briefing board'],
    avoid: ['theme-park local branding'],
    layout: 'WORKSHOP_YARD_INDUSTRIAL_WELCOMING',
    phases: [
      { id: 'PILOT', token: 'PILOT', label: 'Minimum pilot' },
      { id: 'SEMI_PERMANENT', token: 'SEMI', label: 'Preferred semi-permanent' },
      { id: 'FULL', token: 'FULL', label: 'Full digital campus' },
    ],
    rooms: {
      PILOT: [
        room('FLEXIBLE_CLASSROOM', 'Flexible classroom'),
        room('DEVICE_HELP_DESK', 'Device / help desk'),
        room('MOBILE_HARDWARE_CART', 'Mobile hardware cart', { specialist: true }),
        room('MOBILE_NETWORKING_CYBER_CART', 'Mobile networking / cyber cart', { specialist: true }),
        room('PRESENTATION_WALL', 'Presentation wall'),
        room('SECURE_STORAGE', 'Secure storage'),
        room('QUIET_SUPPORT', 'Quiet support'),
        room('STAFF_PLANNING', 'Staff planning'),
        room('HYBRID_LEARNING_RECORDING', 'Hybrid learning / recording'),
      ],
      SEMI: [
        room('FLEXIBLE_CLASSROOM_A', 'Flexible classroom A'),
        room('FLEXIBLE_CLASSROOM_B', 'Flexible classroom B'),
        room('DEVICE_BAR', 'Device bar'),
        room('HARDWARE_REPAIR_LAB', 'Hardware / repair lab', { specialist: true }),
        room('NETWORKING_CYBER_LAB', 'Networking / cyber lab', { specialist: true }),
        room('AI_CLOUD_STUDIO', 'AI / cloud studio', { specialist: true }),
        room('DESIGN_BUILD_STUDIO', 'Design / build studio', { specialist: true, waike: ['assignments'] }),
        room('CAREER_PORTFOLIO_STUDIO', 'Career / portfolio studio', { specialist: true }),
        room('COMMUNITY_ROOM', 'Community room'),
        room('STAFF_OFFICE', 'Staff office'),
        room('STORAGE_WORKROOM', 'Storage / workroom'),
        room('STUDENT_LOUNGE', 'Student lounge / decompression'),
        room('SMALL_MEDIA_HYBRID_STUDIO', 'Small media / hybrid learning studio'),
      ],
      FULL: [
        room('MULTI_ROOM_LEARNING_HUB', 'Multi-room learning hub'),
        room('DEDICATED_LABS', 'Dedicated labs', { specialist: true }),
        room('COMMUNITY_EVENT_SPACE', 'Community event space'),
        room('APPRENTICESHIP_PROJECT_STUDIO', 'Apprenticeship / project studio', { specialist: true }),
        room('DESIGN_BUILD_STUDIO', 'Design / build + prototyping studio', { specialist: true, waike: ['assignments'] }),
        room('RESEARCH_DIGITAL_TWIN_OPS', 'Research + digital twin operations', { specialist: true }),
        room('SHOWCASE_DEMO_GALLERY', 'Showcase / demo gallery', { specialist: true }),
        room('SECURE_DEVICE_DEPOT', 'Secure device depot'),
        room('PARTNER_MEETING_ROOMS', 'Partner meeting rooms'),
        room('HYBRID_LEARNING_STUDIO', 'Hybrid learning / recording studio'),
        room('REGIONAL_POPUP_LAB_STORAGE', 'Regional pop-up lab storage', { specialist: true }),
        room('MENTOR_WORKSPACE', 'Mentor / visiting instructor workspace', { specialist: true }),
        room('INDUSTRY_PROJECT_BRIEFING_ROOM', 'Industry project briefing room', { specialist: true }),
        room('LECTURE_EVENT_SPACE', 'Lecture / event space'),
        room('MEDIA_SOCIAL_CENTER', 'Media / social center'),
      ],
    },
    extra_shared: [],
  },
  {
    id: 'GERMANY',
    slug: 'germany',
    name: 'WAIKE Germany UPNOW',
    atlas_name: 'Germany',
    planning_identity: 'Germany-rooted applied engineering, apprenticeship, Industry 4.0, manufacturing, industrial networking, technical documentation and worker-centered automation node; Ruhr/Rhine-Ruhr is the first anchor concept.',
    planning_model: 'APPRENTICESHIP_INDUSTRY40',
    local_focus: 'Mechatronics, Industry 4.0, technical documentation, worker-respecting automation',
    truth_state: 'PROPOSED',
    character: [
      'German-rooted', 'Ruhr-aware', 'practical', 'precise', 'worker-respecting',
      'youth-friendly', 'adult-respectful', 'hands-on', 'professional',
    ],
    wayfinding: ['precise grid halls', 'quality review board', 'apprenticeship path'],
    avoid: [],
    layout: 'PRECISE_GRID_APPRENTICESHIP_HALLS',
    phases: [
      { id: 'PILOT', token: 'PILOT', label: 'Minimum pilot' },
      { id: 'SEMI_PERMANENT', token: 'SEMI', label: 'Preferred semi-permanent' },
      { id: 'FULL', token: 'FULL', label: 'Full digital campus' },
    ],
    rooms: {
      PILOT: [
        room('FLEXIBLE_CLASSROOM', 'Flexible classroom'),
        room('DEVICE_HELP_DESK', 'Device / help desk'),
        room('MOBILE_HARDWARE_MECHATRONICS_CART', 'Mobile hardware / mechatronics cart', { specialist: true }),
        room('MOBILE_NETWORKING_CYBER_CART', 'Mobile networking / cyber cart', { specialist: true }),
        room('TECHNICAL_DOCUMENTATION_WORKSTATION', 'Technical documentation workstation', { specialist: true, waike: ['assignments'] }),
        room('PRESENTATION_WALL', 'Presentation wall'),
        room('SECURE_STORAGE', 'Secure storage'),
        room('QUIET_SUPPORT', 'Quiet support'),
        room('STAFF_PLANNING', 'Staff planning'),
        room('HYBRID_LEARNING_RECORDING', 'Hybrid learning / recording'),
      ],
      SEMI: [
        room('FLEXIBLE_CLASSROOM_A', 'Flexible classroom A'),
        room('FLEXIBLE_CLASSROOM_B', 'Flexible classroom B'),
        room('DEVICE_BAR', 'Device bar'),
        room('HARDWARE_REPAIR_MECHATRONICS_LAB', 'Hardware / repair / mechatronics lab', { specialist: true }),
        room('NETWORKING_CYBER_LAB', 'Networking / cyber lab', { specialist: true }),
        room('AI_CLOUD_STUDIO', 'AI / cloud studio', { specialist: true }),
        room('INDUSTRY40_DIGITAL_TWIN_STUDIO', 'Industry 4.0 + digital twin studio', { specialist: true, waike: ['courses'] }),
        room('TECHNICAL_DOCUMENTATION_PORTFOLIO_STUDIO', 'Technical documentation + portfolio studio', { specialist: true }),
        room('CAREER_APPRENTICESHIP_STUDIO', 'Career / apprenticeship studio', { specialist: true }),
        room('COMMUNITY_ROOM', 'Community room'),
        room('STAFF_OFFICE', 'Staff office'),
        room('STORAGE_WORKROOM', 'Storage / workroom'),
        room('STUDENT_LOUNGE', 'Student lounge / decompression'),
        room('SMALL_MEDIA_HYBRID_STUDIO', 'Small media / hybrid studio'),
      ],
      FULL: [
        room('MULTI_ROOM_LEARNING_HUB', 'Multi-room learning hub'),
        room('DEDICATED_LABS', 'Dedicated labs', { specialist: true }),
        room('COMMUNITY_EVENT_SPACE', 'Community event space'),
        room('APPRENTICESHIP_PROJECT_STUDIO', 'Apprenticeship / project studio', { specialist: true }),
        room('INDUSTRY40_TWIN_LAB', 'Industry 4.0 + digital twin lab', { specialist: true, waike: ['courses'] }),
        room('MECHATRONICS_SENSOR_STUDIO', 'Mechatronics + sensor studio', { specialist: true }),
        room('RESEARCH_DIGITAL_TWIN_OPS', 'Research + digital twin operations', { specialist: true }),
        room('SHOWCASE_DEMO_GALLERY', 'Showcase / demo gallery', { specialist: true }),
        room('SECURE_DEVICE_DEPOT', 'Secure device depot'),
        room('PARTNER_MEETING_ROOMS', 'Partner meeting rooms'),
        room('HYBRID_LEARNING_STUDIO', 'Hybrid learning / recording studio'),
        room('REGIONAL_POPUP_LAB_STORAGE', 'Regional pop-up lab storage', { specialist: true }),
        room('MENTOR_WORKSPACE', 'Mentor / visiting instructor workspace', { specialist: true }),
        room('EMPLOYER_PROJECT_BRIEFING_ROOM', 'Employer project briefing room', { specialist: true }),
        room('TECHNICAL_DOCUMENTATION_QUALITY_REVIEW_ROOM', 'Technical documentation + quality review room', { specialist: true }),
        room('LECTURE_EVENT_SPACE', 'Lecture / event space'),
        room('MEDIA_SOCIAL_CENTER', 'Media / social center'),
      ],
    },
    extra_shared: [],
  },
  {
    id: 'GAZA',
    slug: 'gaza',
    name: 'WAIKE Gaza UPNOW',
    atlas_name: 'Gaza',
    planning_identity: 'Palestinian-led, trauma-informed, recovery-centered, remote/offline-first education network. This is not a normal fixed campus in the current brief.',
    planning_model: 'RECOVERY_OFFLINE_FIRST_NETWORK',
    local_focus: 'Safe temporary learning, repair / power / connectivity, reconstruction documentation, teacher and caregiver support',
    truth_state: 'PROPOSED',
    character: [
      'Palestinian-led', 'calm', 'safe', 'dignified', 'warm', 'trauma-aware',
      'youth-friendly', 'caregiver-respectful', 'teacher-respecting', 'practical',
      'repair-oriented', 'hopeful without naivety', 'community-rooted without disaster branding',
    ],
    wayfinding: ['temporary learning circles', 'repair and power kits', 'teacher / caregiver guides'],
    avoid: [
      'foreign-NGO aesthetic',
      'disaster tourism',
      'rubble as branding',
      'distressed children as promotion',
      'military/faction aesthetics',
      'sensitive-location maps',
      'performative futurism',
    ],
    layout: 'TEMPORARY_LEARNING_CIRCLES',
    suppress_coordinates: true,
    suppress_sensitive_locations: true,
    phases: [
      { id: 'RECOVERY_NETWORK', token: 'RECOVERY_NETWORK', label: 'Minimum pilot / recovery network' },
      { id: 'SEMI_PERMANENT_LEARNING_HUB', token: 'SEMI', label: 'Preferred semi-permanent learning hub' },
      { id: 'FULL_RECOVERY_EDUCATION_HUB', token: 'RECOVERY', label: 'Full recovery hub digital representation' },
    ],
    rooms: {
      RECOVERY_NETWORK: [
        room('SAFE_TEMPORARY_LEARNING_CIRCLE', 'Safe temporary learning circle', { waike: ['courses'] }),
        room('DEVICE_HELP_DESK', 'Device / help desk or equivalent'),
        room('OFFLINE_LEARNING_KIT', 'Offline learning kit', { specialist: true, coverage: 'IMPLEMENTED_FUNCTIONALLY' }),
        room('MOBILE_DEVICE_REPAIR_KIT', 'Mobile device repair kit', { specialist: true, coverage: 'IMPLEMENTED_FUNCTIONALLY' }),
        room('CHARGING_POWER_KIT', 'Charging / power kit', { specialist: true, coverage: 'IMPLEMENTED_FUNCTIONALLY' }),
        room('PRINTED_CURRICULUM_PACKETS', 'Printed curriculum packets', { coverage: 'IMPLEMENTED_FUNCTIONALLY' }),
        room('TEACHER_GUIDES', 'Teacher guides', { coverage: 'IMPLEMENTED_FUNCTIONALLY' }),
        room('CAREGIVER_GUIDES', 'Caregiver guides', { coverage: 'IMPLEMENTED_FUNCTIONALLY' }),
        room('SECURE_STORAGE_CONTAINER', 'Secure storage container'),
        room('QUIET_SUPPORT_AREA', 'Quiet support area'),
        room('REMOTE_MENTOR_CONNECTION_DEVICE', 'Remote mentor connection device', { specialist: true }),
        room('EMERGENCY_PAUSE_RELOCATION_PLAN', 'Emergency pause / relocation plan', {
          kind: 'OPERATING_CONSTRAINT',
          coverage: 'IMPLEMENTED_FUNCTIONALLY',
          function: 'Operational pause/relocation procedure with no site coordinates',
        }),
      ],
      SEMI: [
        room('LEARNING_CIRCLE_A', 'Flexible learning room / circle A'),
        room('LEARNING_CIRCLE_B', 'Flexible learning room / circle B'),
        room('DEVICE_BAR', 'Device bar'),
        room('HARDWARE_REPAIR_BENCH', 'Hardware / repair bench', { specialist: true }),
        room('LOW_BANDWIDTH_CONNECTIVITY_LAB', 'Low-bandwidth connectivity lab', { specialist: true }),
        room('OFFLINE_SERVER_CONTENT_STATION', 'Offline server / content station', { specialist: true }),
        room('AI_CLOUD_PORTFOLIO_CORNER', 'AI / cloud + portfolio support corner', { specialist: true }),
        room('RECONSTRUCTION_DOCUMENTATION_STUDIO', 'Reconstruction documentation studio', { specialist: true, waike: ['assignments'] }),
        room('TEACHER_SUPPORT_STATION', 'Teacher support station', { specialist: true }),
        room('COMMUNITY_ROOM', 'Community room'),
        room('PSYCHOSOCIAL_DECOMPRESSION_SPACE', 'Psychosocial decompression space'),
        room('SECURE_STORAGE_WORKROOM', 'Secure storage / workroom'),
        room('SMALL_HYBRID_LEARNING_SETUP', 'Small hybrid learning / recording setup'),
      ],
      RECOVERY: [
        room('MULTI_ROOM_LEARNING_HUB', 'Multi-room learning hub'),
        room('DEDICATED_DEVICE_BAR', 'Dedicated device bar'),
        room('REPAIR_LAB', 'Repair lab', { specialist: true }),
        room('NETWORKING_CONNECTIVITY_LAB', 'Networking / connectivity lab', { specialist: true }),
        room('OFFLINE_LEARNING_STUDIO', 'Offline learning studio', { specialist: true, waike: ['courses'] }),
        room('AI_CLOUD_PORTFOLIO_STUDIO', 'AI / cloud / portfolio studio', { specialist: true }),
        room('RECONSTRUCTION_DOCUMENTATION_STUDIO', 'Reconstruction documentation studio', { specialist: true }),
        room('TEACHER_SUPPORT_CENTER', 'Teacher support center', { specialist: true }),
        room('COMMUNITY_LEARNING_ROOM', 'Community learning room'),
        room('PSYCHOSOCIAL_SUPPORT_REFERRAL_SPACE', 'Psychosocial support / referral space'),
        room('SECURE_DEVICE_DEPOT', 'Secure device depot'),
        room('PARTNER_MEETING_ROOM', 'Partner meeting room'),
        room('HYBRID_LEARNING_STUDIO', 'Hybrid learning / recording studio'),
        room('DIGITAL_TWIN_PLANNING_WORKSPACE', 'Digital twin / planning workspace', { specialist: true }),
        room('MOBILE_KIT_STORAGE_DEPLOYMENT_ROOM', 'Mobile kit storage / deployment room', { specialist: true }),
      ],
    },
    extra_shared: [
      room('NO_SENSITIVE_LOCATION_EXPOSURE', 'No sensitive real-world learner or site locations', {
        kind: 'CONSTRAINT',
        coverage: 'IMPLEMENTED_FUNCTIONALLY',
        function: 'Redact coordinates, site maps, and learner locations',
      }),
    ],
  },
  {
    id: 'GRAHAM',
    slug: 'graham-land',
    name: 'WAIKE Graham Land UPNOW',
    atlas_name: 'Graham Land',
    planning_identity: 'Remote-first polar research education and extreme-connectivity node. The brief explicitly rejects a conventional WAIKE-owned campus in Antarctica.',
    planning_model: 'REMOTE_POLAR_DIGITAL_TWIN',
    local_focus: 'Climate / GIS / sensors / NTN / reproducible science / field safety — simulation and education, not a fake station',
    truth_state: 'DIGITAL_TWIN',
    character: [
      'scientific', 'humble', 'precise', 'calm', 'stewardship-centered',
      'research-ready', 'high-tech without theatricality', 'global without colonial framing',
    ],
    wayfinding: ['remote lab', 'simulation layers', 'external station references remain external'],
    avoid: [
      'fake WAIKE research-station claims',
      'adventure-tourism aesthetic',
      'conquering / explorer language',
      'territorial / ownership visuals',
      'decorative polar clichés',
      'implication that WAIKE owns or operates Antarctic territory',
    ],
    layout: 'REMOTE_LAB_PLUS_SIMULATION_LAYERS',
    no_fake_station_claim: true,
    remote_first: true,
    phases: [
      { id: 'REMOTE_LEARNING_LAB', token: 'REMOTE', label: 'Minimum pilot footprint outside Antarctica' },
      { id: 'DIGITAL_TWIN_PARTNER_HOSTED_STUDIO', token: 'TWIN', label: 'Digital twin / partner-hosted studio' },
      { id: 'NON_ANTARCTIC_POLAR_EDUCATION_HUB', token: 'FULL', label: 'Full non-Antarctic polar education hub' },
    ],
    rooms: {
      REMOTE: [
        room('FLEXIBLE_VIRTUAL_CLASSROOM', 'Flexible / virtual classroom'),
        room('DATA_LAB', 'Data lab', { specialist: true, waike: ['courses'] }),
        room('MAPPING_GIS_WORKSTATION', 'Mapping / GIS workstation', { specialist: true }),
        room('DEVICE_HELP_DESK', 'Device / help desk'),
        room('MOBILE_SENSOR_HARDWARE_CART', 'Mobile sensor / hardware cart', { specialist: true }),
        room('NETWORKING_SATCOM_DEMO_CART', 'Networking / satellite-communications demo cart', { specialist: true }),
        room('PRESENTATION_WALL', 'Presentation wall'),
        room('SECURE_STORAGE', 'Secure storage'),
        room('QUIET_SUPPORT', 'Quiet support'),
        room('STAFF_PLANNING', 'Staff planning'),
        room('HYBRID_LEARNING_RECORDING', 'Hybrid learning / recording'),
      ],
      TWIN: [
        room('FLEXIBLE_CLASSROOM_A', 'Flexible classroom A'),
        room('FLEXIBLE_CLASSROOM_B', 'Flexible classroom B'),
        room('CLIMATE_DATA_LAB', 'Climate data lab', { specialist: true }),
        room('GIS_REMOTE_SENSING_STUDIO', 'GIS / remote-sensing studio', { specialist: true }),
        room('HARDWARE_SENSOR_LAB', 'Hardware / sensor lab', { specialist: true }),
        room('NETWORKING_CYBER_LAB', 'Networking / cyber lab', { specialist: true }),
        room('AI_CLOUD_STUDIO', 'AI / cloud studio', { specialist: true }),
        room('FIELD_SAFETY_CLASSROOM', 'Field-safety classroom', { specialist: true }),
        room('PUBLIC_EDUCATION_STUDIO', 'Public education studio'),
        room('STAFF_OFFICE', 'Staff office'),
        room('STORAGE_WORKROOM', 'Storage / workroom'),
        room('STUDENT_LOUNGE', 'Student lounge / decompression'),
        room('MEDIA_HYBRID_STUDIO', 'Media / hybrid studio'),
      ],
      FULL: [
        room('MULTI_ROOM_LEARNING_HUB', 'Multi-room learning hub'),
        room('CLIMATE_DATA_LAB', 'Climate-data lab', { specialist: true }),
        room('GIS_REMOTE_SENSING_LAB', 'GIS / remote-sensing lab', { specialist: true }),
        room('SENSOR_ROBOTICS_BENCH', 'Sensor / robotics bench', { specialist: true }),
        room('NTN_LAB', 'Networking / NTN lab', { specialist: true, waike: ['courses'] }),
        room('AI_CLOUD_REPRODUCIBLE_SCIENCE_STUDIO', 'AI / cloud / reproducible-science studio', { specialist: true }),
        room('PUBLIC_EXHIBIT', 'Public exhibit'),
        room('RESEARCH_POSTER_DEMO_GALLERY', 'Research poster / demo gallery', { specialist: true }),
        room('SECURE_DEVICE_DEPOT', 'Secure device depot'),
        room('PARTNER_MEETING_ROOMS', 'Partner meeting rooms'),
        room('HYBRID_LEARNING_STUDIO', 'Hybrid learning / recording studio'),
        room('CROSS_CAMPUS_OPERATIONS_ROOM', 'Cross-campus operations room', { specialist: true }),
        room('DIGITAL_TWIN_OPERATIONS_AREA', 'Digital twin operations area', { specialist: true }),
        room('LECTURE_EVENT_SPACE', 'Public education / lecture space'),
        room('MEDIA_SOCIAL_CENTER', 'Research communication studio'),
      ],
    },
    extra_shared: [
      room('NO_WAIKE_OWNED_ANTARCTIC_CAMPUS', 'No conventional WAIKE-owned Antarctic campus', {
        kind: 'CONSTRAINT',
        coverage: 'NOT_APPLICABLE',
        function: 'Brief rejects a WAIKE-owned campus in Antarctica; do not imply one',
        evidence: 'PROPOSAL',
      }),
    ],
    twin_layers: [
      room('ANTARCTIC_PENINSULA_GEOGRAPHY', 'Antarctic Peninsula geography', { kind: 'SIMULATION_LAYER', coverage: 'IMPLEMENTED_FUNCTIONALLY', evidence: 'SIMULATION' }),
      room('GRAHAM_LAND_REFERENCE_ZONES', 'Graham Land reference zones', { kind: 'SIMULATION_LAYER', coverage: 'IMPLEMENTED_FUNCTIONALLY', evidence: 'SIMULATION' }),
      room('RESEARCH_STATION_REFERENCE_POINTS', 'Research-station reference points (external)', { kind: 'SIMULATION_LAYER', coverage: 'IMPLEMENTED_FUNCTIONALLY', evidence: 'PARTNER_REFERENCE' }),
      room('PERMITTED_NON_PERMITTED_ASSUMPTIONS', 'Permitted / non-permitted assumptions', { kind: 'SIMULATION_LAYER', coverage: 'IMPLEMENTED_FUNCTIONALLY', evidence: 'PROPOSAL' }),
      room('WEATHER_CLIMATE_VARIABLES', 'Weather / climate variables', { kind: 'SIMULATION_LAYER', coverage: 'IMPLEMENTED_FUNCTIONALLY', evidence: 'SIMULATION' }),
      room('SEA_ICE_SEASONAL_ACCESS', 'Sea ice / seasonal access', { kind: 'SIMULATION_LAYER', coverage: 'IMPLEMENTED_FUNCTIONALLY', evidence: 'SIMULATION' }),
      room('SATELLITE_COMMUNICATIONS', 'Satellite communications', { kind: 'SIMULATION_LAYER', coverage: 'IMPLEMENTED_FUNCTIONALLY', evidence: 'SIMULATION' }),
      room('LOW_BANDWIDTH_TRANSFER', 'Low-bandwidth transfer', { kind: 'SIMULATION_LAYER', coverage: 'IMPLEMENTED_FUNCTIONALLY', evidence: 'SIMULATION' }),
      room('FIELD_CAMP_COMMUNICATION_SCENARIOS', 'Field-camp communication scenarios', { kind: 'SIMULATION_LAYER', coverage: 'IMPLEMENTED_FUNCTIONALLY', evidence: 'SIMULATION' }),
      room('SENSOR_DEPLOYMENT_SIMULATIONS', 'Sensor deployment simulations', { kind: 'SIMULATION_LAYER', coverage: 'IMPLEMENTED_FUNCTIONALLY', evidence: 'SIMULATION' }),
      room('AUTONOMOUS_ROBOT_ROUTE_SCENARIOS', 'Autonomous-robot route scenarios', { kind: 'SIMULATION_LAYER', coverage: 'IMPLEMENTED_FUNCTIONALLY', evidence: 'SIMULATION' }),
      room('ENVIRONMENTAL_CONSTRAINTS', 'Environmental constraints', { kind: 'SIMULATION_LAYER', coverage: 'IMPLEMENTED_FUNCTIONALLY', evidence: 'SIMULATION' }),
      room('PROTECTED_AREA_AWARENESS', 'Protected-area awareness', { kind: 'SIMULATION_LAYER', coverage: 'IMPLEMENTED_FUNCTIONALLY', evidence: 'SIMULATION' }),
      room('LOGISTICS_ROUTES', 'Logistics routes', { kind: 'SIMULATION_LAYER', coverage: 'IMPLEMENTED_FUNCTIONALLY', evidence: 'SIMULATION' }),
      room('EMERGENCY_SCENARIOS', 'Emergency scenarios', { kind: 'SIMULATION_LAYER', coverage: 'IMPLEMENTED_FUNCTIONALLY', evidence: 'SIMULATION' }),
      room('DATA_PIPELINES', 'Data pipelines', { kind: 'SIMULATION_LAYER', coverage: 'IMPLEMENTED_FUNCTIONALLY', evidence: 'SIMULATION' }),
      room('STUDENT_OUTPUTS', 'Student outputs', { kind: 'SIMULATION_LAYER', coverage: 'IMPLEMENTED_FUNCTIONALLY', evidence: 'PROPOSAL' }),
    ],
  },
];

export const SHARED_PROGRAM = SHARED_CAMPUS_PROGRAM;

export const EXAMPLE_REQUIREMENT_IDS = Object.freeze([
  'GARY.FULL.HARDWARE_REPAIR_LAB',
  'GHANA.FULL.MENTOR_WORKSPACE',
  'GUYANA.FULL.CLIMATE_GIS_STUDIO',
  'GEELONG.FULL.DESIGN_BUILD_STUDIO',
  'GERMANY.FULL.INDUSTRY40_TWIN_LAB',
  'GAZA.RECOVERY.OFFLINE_LEARNING_STUDIO',
  'GRAHAM.FULL.NTN_LAB',
]);
